<a href="https://colab.research.google.com/github/DarshanBhovi/pytorch/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
a=torch.tensor([1,2,3,4,5])
b=torch.tensor([5,6,7,8,9])
a
b

tensor([5, 6, 7, 8, 9])

In [2]:
#addition
a+b

tensor([ 6,  8, 10, 12, 14])

In [3]:
torch.add(a,b)

tensor([ 6,  8, 10, 12, 14])

In [5]:
#sub
a-b

tensor([-4, -4, -4, -4, -4])

In [6]:
torch.sub(a,b)

tensor([-4, -4, -4, -4, -4])

In [7]:
#mul
a*b

tensor([ 5, 12, 21, 32, 45])

In [8]:
torch.mul(a,b)

tensor([ 5, 12, 21, 32, 45])

In [9]:
#mod
a%b

tensor([1, 2, 3, 4, 5])

In [11]:
b[1]%a[1]

tensor(0)

In [17]:
#reassignment

b=b+b
b

tensor([20, 24, 28, 32, 36])