<a href="https://colab.research.google.com/github/DarshanBhovi/pytorch/blob/main/Tensor1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
##normal python list
list=[[1,2,4],[5,6,6]]
list

[[1, 2, 4], [5, 6, 6]]

In [6]:
##numpy
np_array=np.random.rand(3,4)
np_array

array([[0.28087661, 0.82929625, 0.22154306, 0.1642    ],
       [0.52667923, 0.55451278, 0.0103968 , 0.82281438],
       [0.29403978, 0.61429722, 0.19786539, 0.71434131]])

In [7]:
## tensor
tensor_array=torch.randn(2,3,4)
tensor_array

tensor([[[ 2.0693, -0.8863, -0.7055, -0.6248],
         [ 0.6547,  0.3714, -0.1782,  0.1186],
         [-1.3091,  0.9867, -0.1535, -1.3419]],

        [[ 0.5632,  0.2625,  0.1851,  0.7595],
         [ 0.3455,  0.3844, -1.1591,  0.6812],
         [-0.2318,  0.1002,  1.5568, -0.5870]]])

In [8]:
## can convert numpy array to tensor
my_tensor=torch.tensor(np_array)
my_tensor

tensor([[0.2809, 0.8293, 0.2215, 0.1642],
        [0.5267, 0.5545, 0.0104, 0.8228],
        [0.2940, 0.6143, 0.1979, 0.7143]], dtype=torch.float64)