<a href="https://colab.research.google.com/github/DarshanBhovi/pytorch/blob/main/tesnsor2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
my_torch1=torch.arange(10)
my_torch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
##reshape, we cant give [2,other than 5] cant reshape
my_torch2=my_torch1.reshape(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
## if we dont no no.of items use -1
my_torch3=torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
my_torch4=my_torch3.reshape(3,-1)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [16]:
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
my_torch5=my_torch3.view(3,-1)
my_torch5

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [18]:
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
#transpose
y=torch.tensor([[1,2],[2,3],[4,5]])
y=y.t()
y

tensor([[1, 2, 4],
        [2, 3, 5]])

In [27]:
#so now transpose make the memory non contigous , then view doesnt work so use reshape
x=y.reshape(6)
x

tensor([1, 2, 4, 2, 3, 5])